/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerIndexRouteImport } from './routes/viewer/index'
import { Route as EngineIndexRouteImport } from './routes/engine/index'
import { Route as ViewerRequirementsRouteImport } from './routes/viewer/requirements'
import { Route as ViewerInstallRouteImport } from './routes/viewer/install'
import { Route as EngineSymbolsRouteImport } from './routes/engine/symbols'
import { Route as EngineShapesRouteImport } from './routes/engine/shapes'
import { Route as EngineIntegrationRouteImport } from './routes/engine/integration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerIndexRoute = ViewerIndexRouteImport.update({
  id: '/viewer/',
  path: '/viewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineIndexRoute = EngineIndexRouteImport.update({
  id: '/engine/',
  path: '/engine/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerRequirementsRoute = ViewerRequirementsRouteImport.update({
  id: '/viewer/requirements',
  path: '/viewer/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerInstallRoute = ViewerInstallRouteImport.update({
  id: '/viewer/install',
  path: '/viewer/install',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineSymbolsRoute = EngineSymbolsRouteImport.update({
  id: '/engine/symbols',
  path: '/engine/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineShapesRoute = EngineShapesRouteImport.update({
  id: '/engine/shapes',
  path: '/engine/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineIntegrationRoute = EngineIntegrationRouteImport.update({
  id: '/engine/integration',
  path: '/engine/integration',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engine/integration': typeof EngineIntegrationRoute
  '/engine/shapes': typeof EngineShapesRoute
  '/engine/symbols': typeof EngineSymbolsRoute
  '/viewer/install': typeof ViewerInstallRoute
  '/viewer/requirements': typeof ViewerRequirementsRoute
  '/engine/': typeof EngineIndexRoute
  '/viewer/': typeof ViewerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engine/integration': typeof EngineIntegrationRoute
  '/engine/shapes': typeof EngineShapesRoute
  '/engine/symbols': typeof EngineSymbolsRoute
  '/viewer/install': typeof ViewerInstallRoute
  '/viewer/requirements': typeof ViewerRequirementsRoute
  '/engine': typeof EngineIndexRoute
  '/viewer': typeof ViewerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engine/integration': typeof EngineIntegrationRoute
  '/engine/shapes': typeof EngineShapesRoute
  '/engine/symbols': typeof EngineSymbolsRoute
  '/viewer/install': typeof ViewerInstallRoute
  '/viewer/requirements': typeof ViewerRequirementsRoute
  '/engine/': typeof EngineIndexRoute
  '/viewer/': typeof ViewerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engine/integration'
    | '/engine/shapes'
    | '/engine/symbols'
    | '/viewer/install'
    | '/viewer/requirements'
    | '/engine/'
    | '/viewer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engine/integration'
    | '/engine/shapes'
    | '/engine/symbols'
    | '/viewer/install'
    | '/viewer/requirements'
    | '/engine'
    | '/viewer'
  id:
    | '__root__'
    | '/'
    | '/engine/integration'
    | '/engine/shapes'
    | '/engine/symbols'
    | '/viewer/install'
    | '/viewer/requirements'
    | '/engine/'
    | '/viewer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineIntegrationRoute: typeof EngineIntegrationRoute
  EngineShapesRoute: typeof EngineShapesRoute
  EngineSymbolsRoute: typeof EngineSymbolsRoute
  ViewerInstallRoute: typeof ViewerInstallRoute
  ViewerRequirementsRoute: typeof ViewerRequirementsRoute
  EngineIndexRoute: typeof EngineIndexRoute
  ViewerIndexRoute: typeof ViewerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/': {
      id: '/viewer/'
      path: '/viewer'
      fullPath: '/viewer/'
      preLoaderRoute: typeof ViewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/': {
      id: '/engine/'
      path: '/engine'
      fullPath: '/engine/'
      preLoaderRoute: typeof EngineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/requirements': {
      id: '/viewer/requirements'
      path: '/viewer/requirements'
      fullPath: '/viewer/requirements'
      preLoaderRoute: typeof ViewerRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/install': {
      id: '/viewer/install'
      path: '/viewer/install'
      fullPath: '/viewer/install'
      preLoaderRoute: typeof ViewerInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/symbols': {
      id: '/engine/symbols'
      path: '/engine/symbols'
      fullPath: '/engine/symbols'
      preLoaderRoute: typeof EngineSymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/shapes': {
      id: '/engine/shapes'
      path: '/engine/shapes'
      fullPath: '/engine/shapes'
      preLoaderRoute: typeof EngineShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/integration': {
      id: '/engine/integration'
      path: '/engine/integration'
      fullPath: '/engine/integration'
      preLoaderRoute: typeof EngineIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineIntegrationRoute: EngineIntegrationRoute,
  EngineShapesRoute: EngineShapesRoute,
  EngineSymbolsRoute: EngineSymbolsRoute,
  ViewerInstallRoute: ViewerInstallRoute,
  ViewerRequirementsRoute: ViewerRequirementsRoute,
  EngineIndexRoute: EngineIndexRoute,
  ViewerIndexRoute: ViewerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
