packages:
  - "apps/*"
  - "packages/*"
overrides:
  "esbuild": "0.26.0"
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@vitejs/plugin-react@6.1.0'
  - vite@8.2.2
onlyBuiltDependencies:
  - electron