export const glFloatSize = Float32Array.BYTES_PER_ELEMENT

// THIS VALUE IS ALSO A CONSTANT IN THE SHADER CODE, UPDATE THERE IF CHANGING HERE
// TODO: MAKE THIS A SHADER UNIFORM INSTEAD OF A CONSTANT
export const PERSPECTIVE_CORRECTION_FACTOR = 0.25
