name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  executables:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Dependencies
        run: npm ci
      # - name: Build
        # run: npm run build:all
      - name: Build macOS
        run: npm run build:mac
      - name: Build Windows
        run: npm run build:win
      - name: Build Linux
        run: npm run build:linux
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
  web-page:
    runs-on: macos-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build:web
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out/web/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
